### ISSUE TITLE
In transaction service throwing class not found makes the tool unusable

### ISSUE THREAD

**Issue by DannyRussellWP** [corda/node-server#2]
In other places within the same file (i.e. line 422, 425 etc) you print the stack trace rather than throwing the exception. By the throwing an exception it breaks the entire tool because you cannot see, the vault, or transactions or the flow list. Better to print the stack trace and return the items that do work.

In the current implementation having the r3 billing app jar in the cordapps folder breaks all of the other cordapps because it cannot find the class StateAndRef<BillingChips>

I have changed line 473 of transactionServiceImpl from
`throw new GenericException(cne.getMessage());`
to 
`cne.printStackTrace();`

And this now enables us to view our vault and transactions (and the 20 odd other cordapps that are working fine)

**Comment by alch3mistdev** [comment]
@DannyRussellWP thanks for the heads-up. The node-server has now been adjusted to allow valid flow constructors to pass through. The printStackTrace() was implemented one method up at line 447, so that invalid constructors can be shielded from the UI. That particular flow will now show an error message if there isn't at LEAST 1 constructor with valid params.

Changes have been committed and new node-explorer binaries are also available. https://github.com/corda/node-explorer/releases

**Comment by DannyRussellWP** [comment]
Thanks @anixon604 . I will test them now

**Comment by DannyRussellWP** [comment]
I can confirm the fix works. Thank you!

**Comment by DannyRussellWP** [comment]
I can confirm this has worked. thank you
